# Generated by Django 4.2.1 on 2023-07-20 07:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="category",
            field=models.CharField(
                choices=[
                    ("TECH", "기술"),
                    ("FOOD", "음식"),
                    ("MUSIC", "음악"),
                    ("EMOTIONS", "감정"),
                    ("SCIENCE", "과학"),
                    ("ARTS", "예술"),
                    ("ANNOUNCE", "공지"),
                    ("MISC", "기타"),
                ],
                default="MISC",
                max_length=10,
            ),
        ),
    ]
