# Generated by Django 4.2.1 on 2023-07-19 08:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0004_category_article_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="name",
        ),
        migrations.AlterField(
            model_name="article",
            name="view_count",
            field=models.PositiveIntegerField(default=0, verbose_name="view count"),
        ),
    ]
