# Generated by Django 4.2.1 on 2023-07-19 08:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0005_remove_category_name_alter_article_view_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="category",
            field=models.CharField(
                choices=[
                    ("테크", "Tech"),
                    ("음식", "Food"),
                    ("감정", "Emotions"),
                    (None, "Miscellaneous"),
                ],
                default=None,
                max_length=255,
            ),
        ),
    ]
