# Generated by Django 4.2.1 on 2023-07-19 20:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0011_alter_category_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="category",
            field=models.CharField(
                choices=[
                    ("TECH", "Technical"),
                    ("FOOD", "Foods"),
                    ("MUSIC", "Musics"),
                    ("EMOTIONS", "Emotions"),
                    ("SCIENCE", "Science"),
                    ("ARTS", "Arts"),
                    ("MISC", "Miscellaneous"),
                ],
                default="MISC",
                max_length=10,
            ),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
